#! /bin/sh
# Autobuilding script : Git -> debian packages
# (c) GPL - Steve Schnepp <steve.schnepp@pwkf.org>

# Has to be launched from the upper svn dir. 
# The dir structure should be like :  
# trunk/
# debian/
# trunk/debian -> ../debian
# packages/

# Stopping on error
set -e

# We don't want localized mesgs
LANG=C

OLDREVISION=$(cd trunk && git describe)
[ -z "$NO_UPDATE" ] && (cd trunk && git pull)
REVISION=$(cd trunk && git describe)

VERSION=$(cd trunk && ./getversion | tr '-' '-')
UPSTREAM=$(cd trunk && git describe --abbrev=0 | tr '-' '-')

# Creating temp source dir
(cd trunk && git archive --format=tar debian-auto --prefix=munin-${UPSTREAM}/ ) | tar x

cd munin-${UPSTREAM}

TMPFILE=$(mktemp)

if [ ! -z "$NO_UPDATE" -o $OLDREVISION != $REVISION ]
then
	# Something has changed, building the changelog
	(
		printf "munin ($VERSION) experimental; urgency=low\n"
		printf "\n" 
		printf "  * Somewhat daily build from devel\n"
		printf "  * git shortlog:\n";
		[ -z "$NO_UPDATE" ] && git shortlog $OLDREVISION..$REVISION 
		printf "\n"
		printf " -- Steve Schnepp <steve.schnepp@munin-monitoring.org>  "
		date --rfc-822
		printf "\n"
	) >> $TMPFILE

	# Create a new one	
	( cat debian/changelog >> $TMPFILE ) && cat $TMPFILE > debian/changelog

	# Building....
	mkdir -p ../logs
	( 
		echo $(date) " - START - Building package $VERSION"
	 	dpkg-buildpackage -us -uc -F -tc "$@"
		echo $(date) " - STOP - Building package $VERSION - retcode : $!"
	) >> ../logs/dpkg-buildpackage-$VERSION.log 
else 
	exit 1
fi

DEB_ARCH=$(dpkg --print-architecture)
if [ -r "../munin_${VERSION}_${DEB_ARCH}.changes" ]
then  
	# Moving everything in packages/ and prepare it for upload
	mkdir -p ../packages/munin
	test -r ../packages/override || touch ../packages/override
	cd ../packages
	mv ../*${VERSION}*.deb munin/
	mv ../*${VERSION}*.dsc munin/
	mv ../*${VERSION}*.tar.gz munin/
	mv ../*${VERSION}*.changes .

	dpkg-scanpackages -m munin override > Packages
	gzip -9 < Packages > Packages.gz
fi

rm $TMPFILE

cd ..
rm munin-${UPSTREAM}
