#! /bin/sh
# Autobuilding script : Git -> debian packages
# (c) GPL - Steve Schnepp <steve.schnepp@pwkf.org>

# Has to be launched from the upper svn dir. 
# The dir structure should be like :  
# ${WORKING_DIR}/
# debian/
# ${WORKING_DIR}/debian -> ../debian
# packages/

# Stopping on error
set -e

WORKING_DIR=$1
if [ -z "$WORKING_DIR" ];
then
	WORKING_DIR="trunk"
else
	shift
fi

# We don't want localized mesgs
LANG=C

OLDREVISION=$(cd ${WORKING_DIR} && git rev-parse HEAD)
[ -z "$NO_UPDATE" ] && (
        cd ${WORKING_DIR} && git fetch origin && git merge origin/devel
        # remove debian-like tags
        git tag | perl -lne 'print if /-(\d+)$/' | xargs -n1 git tag -d
)

REVISION=$(cd ${WORKING_DIR} && git rev-parse HEAD)

UPSTREAM=$(cd ${WORKING_DIR} && ./getversion | tr '-' '-')
VERSION="${UPSTREAM}-999"


if [ -z "$NO_UPDATE" -a "$OLDREVISION" = "$REVISION" ]
then
	echo "Nothing to do, ${UPSTREAM} ($REVISION) is the oldest"	
	exit 1
fi

# Creating temp source dir ...
(cd ${WORKING_DIR} && git archive --format=tar $(git branch | awk '$1 == "*" {print $2}') --prefix=munin-${UPSTREAM}/ ) | tar x

# ... and go there
cd munin-${UPSTREAM}
echo ${UPSTREAM} > RELEASE

TMPFILE=$(mktemp)

# Something has changed, building the changelog, from ${WORKING_DIR}
(
	LOGSPAN=${LOGSPAN:-"$OLDREVISION..$REVISION"}
	cd ../${WORKING_DIR}
	printf "munin ($VERSION) experimental; urgency=low\n"
	printf "\n" 
	printf "  * Somewhat daily build from devel\n"
	printf "  * Authors:\n";
	[ -z "$NO_UPDATE" ] && git shortlog $LOGSPAN | perl -lne 'if (/^(\w[^(]+)/) { $a = $1; $a =~ s/ +$//; print "    $a" }'
	printf "  * Commit log:\n";
	[ -z "$NO_UPDATE" ] && git log --graph --no-merges --oneline $LOGSPAN | perl -lne 'print "    $_"'
	printf "\n"
	printf " -- Steve Schnepp <steve.schnepp@munin-monitoring.org>  "
	date --rfc-822
	printf "\n"
) >> $TMPFILE


# Create a new one
( cat debian/changelog >> $TMPFILE ) && cat $TMPFILE > debian/changelog

# Remove temp changelog
rm -f $TMPFILE

# Building....
mkdir -p ../logs
( 
	echo $(date) " - START - Building package $VERSION"
	dpkg-buildpackage -us -uc -F -tc "$@"
	echo $(date) " - STOP - Building package $VERSION - retcode : $!"
) >> ../logs/dpkg-buildpackage-$VERSION.log 

# Back to ${WORKING_DIR}
cd ..

# Cleanup temp build directory
rm -Rf munin-${UPSTREAM}

DEB_ARCH=$(dpkg --print-architecture)
if [ -r "munin_${VERSION}_${DEB_ARCH}.changes" ]
then  
	# Moving everything in packages/ and prepare it for upload
	mkdir -p packages/munin
	[ -r packages/override ] || touch packages/override

	cd packages
	mv ../*${VERSION}*.deb munin/
	mv ../*${VERSION}*.dsc munin/
	mv ../*${VERSION}*.tar.gz munin/
	mv ../*${VERSION}*.changes .

	dpkg-scanpackages -m munin override > Packages
	bzip2 -9 < Packages > Packages.bz2
fi
